plugins {
    id "me.modmuss50.mod-publish-plugin"
}

publishMods {
    if (project.name == 'fabric')
        file = remapJar.archiveFile
    else
        file = tasks.named('jarJar').get().archiveFile

    modLoaders.add(project.name)
    type = STABLE
    version = project.version
    displayName = "[${project.name.capitalize()}] ${mod_name} ${mod_version}"
    changelog = rootProject.file('CHANGELOG_LATEST.md').text

    curseforge {
        projectId = curseforge_id

        dryRun = providers.environmentVariable("CURSEFORGE_API_KEY").getOrNull() == null
        accessToken = providers.environmentVariable("CURSEFORGE_API_KEY")

        minecraftVersions.addAll(minecraft_version_list.split(','))
        serverRequired = true

        if (project.name == 'fabric')
            optional(fabric_optional_dependencies.split(','))
    }

    modrinth {
        projectId = modrinth_id

        dryRun = providers.environmentVariable("MODRINTH_TOKEN").getOrNull() == null
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")

        minecraftVersions.addAll(minecraft_version_list.split(','))

        if (project.name == 'fabric')
            optional(fabric_optional_dependencies.split(','))
    }
}
