plugins {
    // see https://fabricmc.net/develop/ for new versions
    id 'net.fabricmc.fabric-loom' version '1.15.5' apply false

    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT' apply false

    id 'me.modmuss50.mod-publish-plugin' version '0.8.+' apply false
}

allprojects {
    repositories {
        exclusiveContent {
            forRepository {
                maven {
                    name = 'lionarius-repository'
                    url = 'https://reposilite.lionarius.ru/releases'
                }
            }
            filter {
                includeGroupAndSubgroups('org.mineskin')
            }
        }
    }
}
