# Project
group=net.lionarius
java_version=25

# Common
minecraft_version=26.1
minecraft_version_list=26.1
minecraft_version_range=[26.1, 27)
mod_id=skinrestorer
mod_name=SkinRestorer
mod_version=2.7.0
mod_author=Lionarius
mod_homepage=https://modrinth.com/mod/skinrestorer
mod_sources=https://github.com/Suiranoil/SkinRestorer
mod_issues=https://github.com/Suiranoil/SkinRestorer/issues
license=MIT
credits=
description=A server-side mod for managing skins.

# Dependencies
mineskin_client_version=3.2.1-SNAPSHOT

# Publishing
curseforge_id=443823
modrinth_id=ghrZDhGW

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
