# Project
group=net.lionarius
java_version=21

# Common
minecraft_version=1.21.5
minecraft_version_list=1.21.5
minecraft_version_range=[1.21.5, 1.22)
mod_id=skinrestorer
mod_name=SkinRestorer
mod_version=2.2.1
mod_author=Lionarius
mod_homepage=https://modrinth.com/mod/skinrestorer
mod_sources=https://github.com/Suiranoil/SkinRestorer
mod_issues=https://github.com/Suiranoil/SkinRestorer/issues
license=MIT
credits=
description=A server-side mod for managing skins.

# Dependencies
mineskin_client_version=3.0.1-SNAPSHOT

# ParchmentMC mappings, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.4
parchment_version=2025.03.23

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_loader_version=0.15.0
fabric_api_version=0.119.5+1.21.5
fabric_optional_dependencies=fabric-api

# Forge, see https://files.minecraftforge.net/net/minecraftforge/forge/ for new versions
forge_version=55.0.0
forge_loader_version_range=[55,)
# Forge sometimes skips minor minecraft versions (like 1.20.5)
forge_minecraft_version=1.21.5

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=21.5.0-beta
neoforge_loader_version_range=[4,)

# Publishing
curseforge_id=443823
modrinth_id=ghrZDhGW

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
