plugins {
    id 'multiloader-loader'
    id 'idea'
    id 'eclipse'

    id 'net.minecraftforge.gradle'
    id 'net.minecraftforge.jarjar' version '0.2.3'

    id 'multiloader-publish'
}



jarJar.register()

tasks.named('jar') {
    archiveClassifier = 'slim'
}
tasks.named('jarJar') {
    archiveClassifier = null
}

minecraft {
    mappings channel: 'official', version: "${minecraft_version}"

    accessTransformer = true

    runs {
        configureEach {
            // Mixin requires either specifying the config via command line, or in the Manifest
            args "--mixin.config=${mod_id}.mixins.json"

        }

        register('client') {
            workingDir = file('../run/client')
        }

        register('server') {
            args '--nogui'
            workingDir = file('../run/server')
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${forge_minecraft_version}-${forge_version}")

    annotationProcessor 'net.minecraftforge:eventbus-validator:7.0.1'

    jarJar(implementation("org.mineskin:java-client:${mineskin_client_version}"))
}

// for some reason mixin plugin does not add 'MixinConfigs' to MANIFEST.MF so we do it manually
jar {
    manifest {
        attributes([
                'MixinConfigs': "${mod_id}.mixins.json"
        ])
    }
}
