plugins {
    id 'multiloader-common'

    id 'net.fabricmc.fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    // No mappings needed for 26.1+
    
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'

    implementation("org.mineskin:java-client:${mineskin_client_version}")
}

loom {
    def aw = project.file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    mixin {
        useLegacyMixinAp = false
    }
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
